import { SablonTuru } from "../types";

export const SABLON_GORSEL_LIMITLERI: Record<SablonTuru, number> = {
  "premium-minimal": 4,
  "akademik": 4,
  "etkinlik": 4,
  "bulten": 4,
  "lacivert": 4,
  "mor": 4,
  "kirmizi": 4,
  "turuncu": 4,
  "pembe": 4,
  "teal": 4,
  "altin": 4,
  "kartli-bilgi": 4,
  "kurumsal-resmi": 4,
  "hikaye": 4,
  "fotograf-odakli": 3,
  "kurumsal-kart": 4,
  "pro-minimal": 2,
  "hero-gorselli": 4,
  "split-layout": 3,
  "egitim-panosu": 4,
  "bento-kart": 4,
  "akademik-cizgi": 2,
  "veli-notu": 2,
  "etkinlik-rozetli": 4,
  "dergi-stili": 3,
  "sicak-album": 4,
  "kartli-bilgi-pro": 4,
  "zaman-akisi": 2,
  "cerceveli-klasik": 2,
  "modern-grid": 4,
  "poster-duyuru": 2,
  "foto-kolaj-premium": 4,
  "kurumsal-lacivert": 3,
  "soft-paper": 2,
  "imza-tasarim": 3,
  "kolaj-bulten": 5,
  "dergi-sayfasi": 3,
  "gunluk-akis": 2,
  "foto-albumu": 4,
  "tek-guclu-afis": 1,
  "sinif-rapor-karti": 2,
  "duyuru-panosu": 4,
  "mini-brosur": 2,
  "yan-serit-kurumsal": 3,
  "coklu-faaliyet-raporu": 5,
};

export type TemaliLayout = "klasik" | "sidebar" | "karti";

export const TEMALI_LAYOUT: Partial<Record<SablonTuru, TemaliLayout>> = {
  lacivert: "klasik",
  mor: "sidebar",
  kirmizi: "klasik",
  turuncu: "karti",
  pembe: "sidebar",
  teal: "karti",
  altin: "klasik",
};

export interface SablonMeta {
  id: SablonTuru;
  ad: string;
  chipRenk: string;
  etiket: string;
  maxGorsel: number;
  yeni?: boolean;
  /** Kullanıcıya hangi durumda seçileceği */
  kullanim?: string;
  etiketler?: string[];
}

const PRO_SABLONLAR: SablonMeta[] = [
  { id: "kurumsal-kart", ad: "Kurumsal Kart", chipRenk: "#1d4ed8", etiket: "Kurumsal", maxGorsel: 4, yeni: true, kullanim: "Kurum, hoca ve faaliyet bilgisini net kartlarla verir.", etiketler: ["Kurumsal", "Etüt / Ders", "Fotoğraflı"] },
  { id: "pro-minimal", ad: "Premium Minimal", chipRenk: "#475569", etiket: "Premium", maxGorsel: 2, yeni: true, kullanim: "Az metinli, zarif ve görselsiz kullanıma uygun.", etiketler: ["Minimal", "Premium", "Fotoğrafsız"] },
  { id: "hero-gorselli", ad: "Hero Görselli", chipRenk: "#0ea5e9", etiket: "Fotoğraflı", maxGorsel: 4, yeni: true, kullanim: "Tek güçlü kapak fotoğrafıyla dikkat çeker.", etiketler: ["Fotoğraflı", "Modern", "Premium"] },
  { id: "split-layout", ad: "Split Layout", chipRenk: "#4f46e5", etiket: "Modern", maxGorsel: 3, yeni: true, kullanim: "Sol görsel, sağ bilgi bloklarıyla dengeli iki sütun.", etiketler: ["Modern", "Fotoğraflı"] },
  { id: "egitim-panosu", ad: "Eğitim Panosu", chipRenk: "#2563eb", etiket: "Etüt / Ders", maxGorsel: 4, yeni: true, kullanim: "Ders, alan ve özel notları pano düzeninde gösterir.", etiketler: ["Etüt / Ders", "Kurumsal"] },
  { id: "bento-kart", ad: "Bento Kart", chipRenk: "#7c3aed", etiket: "Modern", maxGorsel: 4, yeni: true, kullanim: "Farklı boy kartlarla modern dashboard hissi verir.", etiketler: ["Modern", "Premium", "Fotoğraflı"] },
  { id: "akademik-cizgi", ad: "Akademik Çizgi", chipRenk: "#0f172a", etiket: "Kurumsal", maxGorsel: 2, yeni: true, kullanim: "Ciddi, çizgisel ve disiplinli okul/etüt dili.", etiketler: ["Kurumsal", "Etüt / Ders"] },
  { id: "veli-notu", ad: "Veli Notu Odaklı", chipRenk: "#92400e", etiket: "Sıcak", maxGorsel: 2, yeni: true, kullanim: "Güven veren metni öne çıkaran sade düzen.", etiketler: ["Sıcak / Samimi", "Fotoğrafsız"] },
  { id: "etkinlik-rozetli", ad: "Etkinlik Rozetli", chipRenk: "#15803d", etiket: "Etkinlik", maxGorsel: 4, yeni: true, kullanim: "Faaliyet türlerini rozetlerle vurgular.", etiketler: ["Etkinlik / Sosyal", "Fotoğraflı"] },
  { id: "dergi-stili", ad: "Dergi Stili", chipRenk: "#be123c", etiket: "Premium", maxGorsel: 3, yeni: true, kullanim: "Editoryal, premium ve dikkat çekici görünüm.", etiketler: ["Premium", "Modern"] },
  { id: "sicak-album", ad: "Sıcak Albüm", chipRenk: "#c2410c", etiket: "Sıcak", maxGorsel: 4, yeni: true, kullanim: "Fotoğraflı, yumuşak ve veliye samimi gelen yapı.", etiketler: ["Sıcak / Samimi", "Fotoğraflı"] },
  { id: "kartli-bilgi-pro", ad: "Kartlı Bilgi Gelişmiş", chipRenk: "#0d9488", etiket: "Etüt / Ders", maxGorsel: 4, yeni: true, kullanim: "Ders, özet, sorumlu ve kurum bilgisini ayrı kartlar.", etiketler: ["Etüt / Ders", "Modern"] },
  { id: "zaman-akisi", ad: "Zaman Akışı", chipRenk: "#4338ca", etiket: "Etüt / Ders", maxGorsel: 2, yeni: true, kullanim: "Faaliyetleri timeline mantığıyla anlatır.", etiketler: ["Etüt / Ders", "Kurumsal"] },
  { id: "cerceveli-klasik", ad: "Çerçeveli Klasik", chipRenk: "#78350f", etiket: "Klasik", maxGorsel: 2, yeni: true, kullanim: "Düzenli, geleneksel ve resmi duyurular için.", etiketler: ["Kurumsal", "Fotoğrafsız"] },
  { id: "modern-grid", ad: "Modern Grid", chipRenk: "#0284c7", etiket: "Modern", maxGorsel: 4, yeni: true, kullanim: "Izgara bilgi bloklarıyla net ve çağdaş.", etiketler: ["Modern", "Fotoğraflı"] },
  { id: "poster-duyuru", ad: "Poster Duyuru", chipRenk: "#dc2626", etiket: "Etkinlik", maxGorsel: 2, yeni: true, kullanim: "Büyük başlık, güçlü çağrı ve sade alt bilgi.", etiketler: ["Etkinlik / Sosyal", "Modern"] },
  { id: "foto-kolaj-premium", ad: "Foto Kolaj Premium", chipRenk: "#0891b2", etiket: "Fotoğraflı", maxGorsel: 4, yeni: true, kullanim: "2-4 görsel ile şık kolaj ve dengeli metin.", etiketler: ["Fotoğraflı", "Premium"] },
  { id: "kurumsal-lacivert", ad: "Kurumsal Lacivert", chipRenk: "#172554", etiket: "Kurumsal", maxGorsel: 3, yeni: true, kullanim: "Güçlü lacivert dil, az ama etkili bloklar.", etiketler: ["Kurumsal", "Premium"] },
  { id: "soft-paper", ad: "Soft Paper", chipRenk: "#a16207", etiket: "Sıcak", maxGorsel: 2, yeni: true, kullanim: "Kağıt hissi veren sakin ve premium görünüm.", etiketler: ["Sıcak / Samimi", "Minimal"] },
  { id: "imza-tasarim", ad: "İmza Tasarım", chipRenk: "#334155", etiket: "Premium", maxGorsel: 3, yeni: true, kullanim: "Kurum ve sorumlu bilgisini karakterli imza alanıyla verir.", etiketler: ["Premium", "Kurumsal"] },
];

const YENI_LAYOUT_SABLONLAR: SablonMeta[] = [
  {
    id: "kolaj-bulten",
    ad: "Kolaj Bülten",
    chipRenk: "#ea580c",
    etiket: "Bülten",
    maxGorsel: 5,
    yeni: true,
    kullanim: "Kolaj Bülten — Çoklu fotoğraflı günlük bilgilendirme; etiketli kolaj + metin.",
    etiketler: ["Çoklu Foto", "Bülten", "Fotoğraflı"],
  },
  {
    id: "dergi-sayfasi",
    ad: "Dergi Sayfası",
    chipRenk: "#18181b",
    etiket: "Bülten",
    maxGorsel: 3,
    yeni: true,
    kullanim: "Gazete/dergi düzeni; iki sütun metin ve yan görsel sütunu.",
    etiketler: ["Bülten", "Kurumsal"],
  },
  {
    id: "gunluk-akis",
    ad: "Günlük Akış",
    chipRenk: "#4338ca",
    etiket: "Akış",
    maxGorsel: 2,
    yeni: true,
    kullanim: "Günlük Akış — Ders ve etkinlikleri sırayla timeline ile gösterir.",
    etiketler: ["Akış", "Etüt / Ders"],
  },
  {
    id: "foto-albumu",
    ad: "Fotoğraf Albümü",
    chipRenk: "#0ea5e9",
    etiket: "Etkinlik",
    maxGorsel: 4,
    yeni: true,
    kullanim: "4 fotoğraflı albüm; gezi, piknik ve etkinlik paylaşımları için.",
    etiketler: ["Çoklu Foto", "Etkinlik / Sosyal", "Fotoğraflı"],
  },
  {
    id: "tek-guclu-afis",
    ad: "Tek Güçlü Afiş",
    chipRenk: "#db2777",
    etiket: "Etkinlik",
    maxGorsel: 1,
    yeni: true,
    kullanim: "Tek hero görsel + güçlü başlık bandı; sosyal medya afişi hissi.",
    etiketler: ["Fotoğraflı", "Modern", "Etkinlik / Sosyal"],
  },
  {
    id: "sinif-rapor-karti",
    ad: "Sınıf Rapor Kartı",
    chipRenk: "#15803d",
    etiket: "Kurumsal",
    maxGorsel: 2,
    yeni: true,
    kullanim: "Sınıf Rapor Kartı — Kazanım, ev tekrarı ve hoca notunu kartlarla sunar.",
    etiketler: ["Kurumsal", "Etüt / Ders"],
  },
  {
    id: "duyuru-panosu",
    ad: "Duyuru Panosu",
    chipRenk: "#78716c",
    etiket: "Etkinlik",
    maxGorsel: 4,
    yeni: true,
    kullanim: "Panoya asılı not/kart parçaları; başlık, faaliyet ve hatırlatma ayrı.",
    etiketler: ["Etkinlik / Sosyal", "Modern"],
  },
  {
    id: "mini-brosur",
    ad: "Mini Broşür",
    chipRenk: "#0284c7",
    etiket: "Broşür",
    maxGorsel: 2,
    yeni: true,
    kullanim: "Katlanmış broşür düzeni; WhatsApp paylaşımına uygun kompakt yapı.",
    etiketler: ["Broşür", "Kurumsal"],
  },
  {
    id: "yan-serit-kurumsal",
    ad: "Yan Şerit Kurumsal",
    chipRenk: "#1d4ed8",
    etiket: "Kurumsal",
    maxGorsel: 3,
    yeni: true,
    kullanim: "Sol dikey kurum şeridi + asimetrik içerik; resmi bilgilendirme.",
    etiketler: ["Kurumsal", "Modern"],
  },
  {
    id: "coklu-faaliyet-raporu",
    ad: "Çoklu Faaliyet Raporu",
    chipRenk: "#7e22ce",
    etiket: "Bülten",
    maxGorsel: 5,
    yeni: true,
    kullanim: "Birden fazla faaliyeti satır satır; yaz kursu ve günlük program için.",
    etiketler: ["Çoklu Foto", "Bülten", "Etüt / Ders"],
  },
];

export const SABLON_LISTESI: SablonMeta[] = [
  {
    id: "akademik",
    ad: "Kurumsal Mavi",
    chipRenk: "#1e3a5f",
    etiket: "Kurumsal",
    maxGorsel: 4,
    kullanim: "Günlük ders ve etüt bilgilendirmeleri için ideal.",
    etiketler: ["3–4 görsel", "Kurumsal"],
  },
  {
    id: "etkinlik",
    ad: "Etkinlik Yeşil",
    chipRenk: "#14532d",
    etiket: "Etkinlik",
    maxGorsel: 4,
    kullanim: "Etkinlikler ve gezi duyurularında güçlü görünür.",
    etiketler: ["Etkinlik", "Fotoğraflı"],
  },
  {
    id: "bulten",
    ad: "Bülten Kahve",
    chipRenk: "#78350f",
    etiket: "Bülten",
    maxGorsel: 4,
    kullanim: "Çoklu görsel ve haftalık özet paylaşımları için.",
    etiketler: ["4 görsel", "Özet"],
  },
  { id: "lacivert",        ad: "Resmi Lacivert",  chipRenk: "#0f172a", etiket: "Temalı",    maxGorsel: 4 },
  { id: "mor",             ad: "Rehberlik Mor",   chipRenk: "#4c1d95", etiket: "Temalı",    maxGorsel: 4 },
  { id: "kirmizi",         ad: "Enerji Kırmızı",  chipRenk: "#991b1b", etiket: "Temalı",    maxGorsel: 4 },
  { id: "turuncu",         ad: "Bahar Turuncu",   chipRenk: "#c2410c", etiket: "Temalı",    maxGorsel: 4 },
  { id: "pembe",           ad: "Anaokulu Pembe",  chipRenk: "#9d174d", etiket: "Temalı",    maxGorsel: 4 },
  { id: "teal",            ad: "Doğa Teal",       chipRenk: "#115e59", etiket: "Temalı",    maxGorsel: 4 },
  {
    id: "altin",
    ad: "Altın Sarı",
    chipRenk: "#92400e",
    etiket: "Temalı",
    maxGorsel: 4,
    kullanim: "Fotoğraflı ve sıcak veli bilgilendirmeleri için.",
    etiketler: ["Fotoğraflı", "Sıcak"],
  },
  {
    id: "premium-minimal",
    ad: "Premium Minimal",
    chipRenk: "#334155",
    etiket: "Minimal",
    maxGorsel: 4,
    yeni: true,
    kullanim: "Az metinli, sade ve kurumsal afişler için.",
    etiketler: ["Az metin", "Kurumsal", "Görselsiz uygun"],
  },
  {
    id: "kartli-bilgi",
    ad: "Kartlı Bilgi",
    chipRenk: "#2563eb",
    etiket: "Kartlı",
    maxGorsel: 4,
    yeni: true,
    kullanim: "Ders / etüt çalışmalarını net göstermek için.",
    etiketler: ["Ders/etüt", "Detaylı bilgi"],
  },
  {
    id: "kurumsal-resmi",
    ad: "Kurumsal Resmi",
    chipRenk: "#1e293b",
    etiket: "Resmi",
    maxGorsel: 4,
    yeni: true,
    kullanim: "Resmi duyuru ve kurumsal bilgilendirme için.",
    etiketler: ["Kurumsal", "Görselsiz uygun"],
  },
  {
    id: "hikaye",
    ad: "Hikaye Stili",
    chipRenk: "#c8956c",
    etiket: "Hikaye",
    maxGorsel: 4,
    yeni: true,
    kullanim: "Sıcak, hikâye anlatımı hissi veren paylaşımlar için.",
    etiketler: ["Sıcak", "Fotoğraflı"],
  },
  {
    id: "fotograf-odakli",
    ad: "Fotoğraf Odaklı",
    chipRenk: "#0ea5e9",
    etiket: "Kolaj",
    maxGorsel: 3,
    yeni: true,
    kullanim: "1–2 güçlü fotoğrafla dikkat çekici bilgilendirme için.",
    etiketler: ["Fotoğraflı", "Dikkat çekici"],
  },
  ...PRO_SABLONLAR,
  ...YENI_LAYOUT_SABLONLAR,
];

export const YENI_LAYOUT_SABLON_IDS = YENI_LAYOUT_SABLONLAR.map((s) => s.id);
export const PRO_SABLON_IDS = PRO_SABLONLAR.map((s) => s.id);
